In [1]:
import pandas as pd 
import numpy as np 


In [2]:
train_data = pd.read_csv('train_data.csv')
test_data = pd.read_csv('test.csv')

In [3]:
train_data.head()

PassengerId                                               Name  \
0            1                            Braund, Mr. Owen Harris   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2            3                             Heikkinen, Miss. Laina   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4            5                           Allen, Mr. William Henry   

             Ticket Cabin     Sex   Age     Fare  Parch  Pclass  SibSp  \
0         A/5 21171   NaN    male  22.0   7.2500      0       3      1   
1          PC 17599   C85  female  38.0  71.2833      0       1      1   
2  STON/O2. 3101282   NaN  female  26.0   7.9250      0       3      0   
3            113803  C123  female  35.0  53.1000      0       1      1   
4            373450   NaN    male  35.0   8.0500      0       3      0   

  Embarked  Survived  
0        S         0  
1        C         1  
2        S         1  
3        S         1  
4        S         0

In [4]:
test_data.head()

Name  PassengerId   Ticket Cabin  \
0                              Kelly, Mr. James          892   330911   NaN   
1              Wilkes, Mrs. James (Ellen Needs)          893   363272   NaN   
2                     Myles, Mr. Thomas Francis          894   240276   NaN   
3                              Wirz, Mr. Albert          895   315154   NaN   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)          896  3101298   NaN   

      Sex   Age     Fare  Parch  Pclass  SibSp Embarked  
0    male  34.5   7.8292      0       3      0        Q  
1  female  47.0   7.0000      0       3      1        S  
2    male  62.0   9.6875      0       2      0        Q  
3    male  27.0   8.6625      0       3      0        S  
4  female  22.0  12.2875      1       3      1        S

In [5]:
train_data.drop(['Name','PassengerId','Ticket'],inplace = True,axis =1)
test_data.drop(['Name','PassengerId','Ticket'],inplace = True,axis=1)

In [6]:
train_data.head()

Cabin     Sex   Age     Fare  Parch  Pclass  SibSp Embarked  Survived
0   NaN    male  22.0   7.2500      0       3      1        S         0
1   C85  female  38.0  71.2833      0       1      1        C         1
2   NaN  female  26.0   7.9250      0       3      0        S         1
3  C123  female  35.0  53.1000      0       1      1        S         1
4   NaN    male  35.0   8.0500      0       3      0        S         0

In [7]:
test_data.head()

Cabin     Sex   Age     Fare  Parch  Pclass  SibSp Embarked
0   NaN    male  34.5   7.8292      0       3      0        Q
1   NaN  female  47.0   7.0000      0       3      1        S
2   NaN    male  62.0   9.6875      0       2      0        Q
3   NaN    male  27.0   8.6625      0       3      0        S
4   NaN  female  22.0  12.2875      1       3      1        S

In [8]:
train_data.isnull().sum()

Cabin       687
Sex           0
Age         177
Fare          0
Parch         0
Pclass        0
SibSp         0
Embarked      0
Survived      0
dtype: int64

In [9]:
test_data.isnull().sum()

Cabin       327
Sex           0
Age          86
Fare          1
Parch         0
Pclass        0
SibSp         0
Embarked      0
dtype: int64

In [10]:
train_data['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64',

In [11]:
train_data['Cabin'].fillna(0,inplace = True)
test_data["Cabin"].fillna(0,inplace= True)

In [12]:
train_data.head()

Cabin     Sex   Age     Fare  Parch  Pclass  SibSp Embarked  Survived
0     0    male  22.0   7.2500      0       3      1        S         0
1   C85  female  38.0  71.2833      0       1      1        C         1
2     0  female  26.0   7.9250      0       3      0        S         1
3  C123  female  35.0  53.1000      0       1      1        S         1
4     0    male  35.0   8.0500      0       3      0        S         0

In [13]:
def cabin(value):
    val_dict = {
        'A' : 6,
        'B' : 5,
        'C' : 4,
        'D' : 3,
        'E' : 2,
        'F' : 1,
        'T' : 1   ## Taking T same as F, taking it to be an error     
    }
    return val_dict.get(str(value)[0], 0)
train_data['Cabin'] = train_data['Cabin'].apply(cabin)
test_data['Cabin'] =test_data['Cabin'].apply(cabin)

In [14]:
train_data.head()

Cabin     Sex   Age     Fare  Parch  Pclass  SibSp Embarked  Survived
0      0    male  22.0   7.2500      0       3      1        S         0
1      4  female  38.0  71.2833      0       1      1        C         1
2      0  female  26.0   7.9250      0       3      0        S         1
3      4  female  35.0  53.1000      0       1      1        S         1
4      0    male  35.0   8.0500      0       3      0        S         0

In [15]:
test_data.head()


Cabin     Sex   Age     Fare  Parch  Pclass  SibSp Embarked
0      0    male  34.5   7.8292      0       3      0        Q
1      0  female  47.0   7.0000      0       3      1        S
2      0    male  62.0   9.6875      0       2      0        Q
3      0    male  27.0   8.6625      0       3      0        S
4      0  female  22.0  12.2875      1       3      1        S

In [16]:
mean = train_data['Age'].median()
train_data['Age'].fillna(mean,inplace = True)
test_data['Age'].fillna(mean,inplace = True)

In [17]:
train_data.isnull().sum()

Cabin       0
Sex         0
Age         0
Fare        0
Parch       0
Pclass      0
SibSp       0
Embarked    0
Survived    0
dtype: int64

In [18]:
test_data.isnull().sum()

Cabin       0
Sex         0
Age         0
Fare        1
Parch       0
Pclass      0
SibSp       0
Embarked    0
dtype: int64

In [19]:
meanfare = test_data['Fare'].mean()
test_data['Fare'].fillna(mean,inplace = True)

In [20]:
test_data.isnull().sum()

Cabin       0
Sex         0
Age         0
Fare        0
Parch       0
Pclass      0
SibSp       0
Embarked    0
dtype: int64

In [21]:
train_data.head()

Cabin     Sex   Age     Fare  Parch  Pclass  SibSp Embarked  Survived
0      0    male  22.0   7.2500      0       3      1        S         0
1      4  female  38.0  71.2833      0       1      1        C         1
2      0  female  26.0   7.9250      0       3      0        S         1
3      4  female  35.0  53.1000      0       1      1        S         1
4      0    male  35.0   8.0500      0       3      0        S         0

In [22]:
x= train_data.iloc[:,:-1].values
y = train_data.iloc[:,-1].values

In [23]:
print(x[:5,:])

[[0 'male' 22.0 7.25 0 3 1 'S']
 [4 'female' 38.0 71.2833 0 1 1 'C']
 [0 'female' 26.0 7.925 0 3 0 'S']
 [4 'female' 35.0 53.1 0 1 1 'S']
 [0 'male' 35.0 8.05 0 3 0 'S']]


In [24]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [1,7])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [25]:
print(x[:5,:])

[[0.0 1.0 0.0 0.0 1.0 0 22.0 7.25 0 3 1]
 [1.0 0.0 1.0 0.0 0.0 4 38.0 71.2833 0 1 1]
 [1.0 0.0 0.0 0.0 1.0 0 26.0 7.925 0 3 0]
 [1.0 0.0 0.0 0.0 1.0 4 35.0 53.1 0 1 1]
 [0.0 1.0 0.0 0.0 1.0 0 35.0 8.05 0 3 0]]


In [26]:
x_test = test_data.iloc[:,:].values
print(x_test[:5,:])

[[0 'male' 34.5 7.8292 0 3 0 'Q']
 [0 'female' 47.0 7.0 0 3 1 'S']
 [0 'male' 62.0 9.6875 0 2 0 'Q']
 [0 'male' 27.0 8.6625 0 3 0 'S']
 [0 'female' 22.0 12.2875 1 3 1 'S']]


In [27]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [1,7])], remainder='passthrough')
x_test = np.array(ct.fit_transform(x_test))

In [28]:
print(x_test[:5,6:8])

[[34.5 7.8292]
 [47.0 7.0]
 [62.0 9.6875]
 [27.0 8.6625]
 [22.0 12.2875]]


In [29]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x[:,6:8] = sc.fit_transform(x[:,6:8])
x_test[:,6:8] = sc.transform(x_test[:,6:8])


In [30]:
from sklearn.svm import SVC
reg = SVC(kernel = 'rbf',degree=4,gamma='scale',class_weight='balanced')
reg.fit(x,y)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight='balanced', coef0=0.0,
    decision_function_shape='ovr', degree=4, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [31]:
y_pred= reg.predict(x_test)

In [32]:
print(y_pred)

[0 1 0 0 1 0 1 0 1 0 0 0 1 0 1 1 0 0 1 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 1 0 1
 1 0 0 0 1 0 1 1 0 0 0 1 1 1 0 1 1 0 0 0 0 0 1 0 0 0 1 1 1 1 0 1 0 1 0 1 1
 1 0 0 1 0 1 1 1 0 0 0 0 1 1 1 1 1 0 1 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0
 1 1 1 1 0 0 1 1 1 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0
 0 0 1 0 0 1 0 0 1 1 1 1 1 1 1 0 0 1 0 0 1 1 0 0 0 0 0 1 1 1 1 1 0 1 1 0 1
 0 1 0 0 0 0 0 0 0 1 0 1 1 0 1 1 1 1 1 0 0 1 0 1 0 0 0 0 1 0 0 1 0 1 0 1 0
 1 0 1 1 0 1 0 0 0 1 0 0 1 0 0 0 1 1 1 1 0 0 0 1 1 0 1 1 1 0 1 0 0 0 0 0 1
 0 0 0 1 1 0 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 1 1 1 0 0 1 0 0 0 1 0 0 0 0
 1 0 0 0 0 1 0 0 1 1 1 1 0 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0
 1 0 1 0 0 0 0 0 0 0 1 0 1 0 1 0 1 1 0 0 0 1 0 1 0 0 1 0 1 1 0 1 0 0 1 1 0
 0 1 0 0 1 1 1 0 0 0 0 0 1 1 0 1 0 0 0 0 1 1 1 0 0 1 0 1 0 0 1 0 1 0 1 1 0
 1 1 1 1 1 1 0 1 0 0 0]
